### ISSUE TITLE
NFT pending queue

### ISSUE THREAD

**Issue by korzewski** [anmolnetwork/anmol-node#22]
### Off-chain workers initialisation

1. New NFT would be added to pending queue
2. Off-chain worker checks pending queue and if any then starts a worker (simple console log)

**Comment by nblogist** [comment]
@korzewski can you please elaborate the console log part?

**Comment by korzewski** [comment]
> @korzewski can you please elaborate the console log part?

Sure, this ticket is about simple off-chain worker triggers. When `on-chain` add something to the queue, `off-chain` listen to that. When `off-chain` worker decides to execute a job on particular "pending nft" then display it as a console log. https://github.com/anmolnetwork/anmol-node/pull/25/files#diff-9340a89ab12e3b4b5b5e36714cb73d3c82979532d77c70c143ab488ef416154bR139

This would be replaced with a real logic in next PR's eg. #23
